require: rubocop-rspec

Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*_spec.rb"

RSpec/NestedGroups:
  Max: 4
RSpec/MultipleMemoizedHelpers:
  Enabled: false

AllCops:
  NewCops: "disable"
  Exclude:
    - "db/schema.rb"
